# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: 20 Dummy Jobs - React Repository One

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  build1:
    runs-on: ubuntu-latest
    name: Build1
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ 14 }}
      - run: npm install

  build2:
    runs-on: ubuntu-latest
    name: Build2
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ 14 }}
      - run: npm install
